### ISSUE TITLE
Transkribus 1.9+ local export failure

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/TranskribusSwtGui#1]
## Actual Behavior

I'm facing a NPE when I try to export Transcriptions from local Files/Images as ALTO + PAGE with Transkribus 1.9.1 Client GUI and there's no data in the chosen export-Destination.

**_Note_** : 
**As this fork starts with Transkribus 1.10.1, this Issue still holds.**

[ulb-sachsen-anhalt-transkribus-1.9.1-01.zip](https://github.com/Transkribus/TranskribusSwtGui/files/3983778/ulb-sachsen-anhalt-transkribus-1.9.1-01.zip)

## Expected Behavior

Export Data in PAGE and ALTO and do not yield Errors.

Please note
_I've attached the root doc.xml as well as the output into the page-Subfolder which gets created in the ZIP-File. The actual TIF-File is not included_

## Plattform
Starting Transkribus - first trying to find java, your OS = linux-gnu
Found java executable in PATH
Java bin = java
Checking java version of: java
Java version = 1.8.0_232 (OpenJDK)

## Reproduce
1. Open Folder with large Tif-Image (7346 x 10791)
2. Include some minimal Transcriptions
3. Click "Export document" => "Export options" [check also "Export ALTO", otherwise defaults] => "OK"

=> Opens Error Dialog Pane

stdout-Log
```
14:17:50.457 WARN  [pool-15-thread-1] eu.transkribus.core.io.LocalDocWriter - Could not update transcript image dimensions - page object is null - should not happen for local docs: file:/home/hartwig/Dokumente/Quarantaene/Transkibus-1.9.1./page/1681877805_J_0006_0004.xml
14:17:58.134 ERROR [main] eu.transkribus.swt_gui.mainwidget.TrpMainWidget - Export error - Error during export of document - null
java.lang.NullPointerException: null
	at eu.transkribus.swt_gui.mainwidget.storage.Storage.exportDocument(Storage.java:2305)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$28.run(TrpMainWidget.java:4070)
	at eu.transkribus.swt.progress.ProgressBarDialog$1.call(ProgressBarDialog.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:17:59.653 ERROR [main] eu.transkribus.swt_gui.mainwidget.TrpMainWidget - Export error - null - null
java.lang.NullPointerException: null
	at eu.transkribus.swt_gui.mainwidget.storage.Storage.exportDocument(Storage.java:2305)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$28.run(TrpMainWidget.java:4070)
	at eu.transkribus.swt.progress.ProgressBarDialog$1.call(ProgressBarDialog.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

## Further Investigations
After some experiments we found a working combination with Transkribus 1.5.4 and Oracle Java 1.8.0_131-b11 to export Data as PAGE and ALTO.

On can even import existing ALTO Data and have Transkribus transform this into it's own PAGE Data, when the input ALTO is V2.

BUT

using the same Oracle Java Version as above, an update to Transkribus 1.6.0 results in a similar (silent) export issue. Looks like the client export is already broken since Version 1.6.0 ?

[stweil](https://github.com/stweil) did also some investigation in this Issue

>  I get the same error when trying to export PAGE.
>
> Software used: Transkribus-1.9.1 with OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-2, mixed mode, sharing).

**Comment by M3ssman** [comment]
To make things even worse, on Ubuntu there's a minor problem just to run the Maven build: 

```
[ERROR] 
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/m3ssman/.m2/repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1/launch4j-maven-plugin-1.5.1-workdir-linux/bin/windres": error=2, Datei oder Verzeichnis nicht gefunden
    at net.sf.launch4j.Builder.build (Builder.java:144)
    at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute (Launch4jMojo.java:353)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/m3ssman/.m2/repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1/launch4j-maven-plugin-1.5.1-workdir-linux/bin/windres": error=2, Datei oder Verzeichnis nicht gefunden
```

This is related to an issue back from 2015: https://github.com/lukaszlenart/launch4j-maven-plugin/issues/4

Still, there's no fix available. Suggested workaround is to install additional libs for:
* lib32z1
* lib32ncurses5
* lib32bz2-1.0

**Comment by M3ssman** [comment]
It was sufficient to run `sudo apt-get install lib32ncurses5` to haven Maven create the packages 
* plain (no JRE, size 120 MB)
* Windows (+jre-1.8.0_172-win64, hence size > 200 MB)
* MAC (+jre-1.8.0_45-mac64, hence size > 188 MB)

**Comment by novacellus** [comment]
The issue seems to persist on Ubuntu 20.04. Tested with Transkribus 1.11 and 1.5.4 with OpenJDK and Oracle Java 1.8.0.261.

**Comment by data443-cboyd** [comment]
I have the same issue on Ubuntu 20.04 with launch4j, the package lib32ncurses5 is not available in the repo, it has been replaced by lib32ncurses6.

**Comment by M3ssman** [comment]
@novacellus @data443-cboyd 

Please note, the official Transkribus GUI Distribution has not and probably will never ever change  this issue. From their of view it is accepted behavior. It is a precondition to use the official Transkribus WebServices to work with the official Application from transkribus.eu, which requires you also to have a valid Online Account, which you might use to login and authenticate and so on. I had some conversation with the people from transkribus.eu regarding this Issue. IIRC, local export is disabled since V 1.6 of Transkribus, although this has not been communicated.

If you want to work in local mode anyway, you might clone the fork from this repo and build it on your own. You only need OpenJDK 8+ and Maven 3.6+ and run `mvn package` at root dir to do so. 

I'm doing the build for my colleagues for Windows and Linux-Distributions on an Ubuntu 18.04 LTS with OpenJDK 11 and Maven 3.6 and it works quite reasonably. There's some trouble with MacOS, but this seems to be related rather to general problems with running 64bit JavaApps on Mac OS.
